MODEL:
  META_ARCHITECTURE: "panoptic_deeplab"
  BN_MOMENTUM: 0.01
  BACKBONE:
    NAME: "resnet50"
    DILATION: (False, False, False)
    PRETRAINED: True
  DECODER:
    IN_CHANNELS: 2048
    FEATURE_KEY: "res5"
    DECODER_CHANNELS: 256
    ATROUS_RATES: (3, 6, 9)
  PANOPTIC_DEEPLAB:
    LOW_LEVEL_CHANNELS: (1024, 512, 256)
    LOW_LEVEL_KEY: ["res4", "res3", "res2"]
    LOW_LEVEL_CHANNELS_PROJECT: (128, 64, 32)
    INSTANCE:
      ENABLE: True
      LOW_LEVEL_CHANNELS_PROJECT: (64, 32, 16)
      DECODER_CHANNELS: 128
      HEAD_CHANNELS: 32
      ASPP_CHANNELS: 256
      NUM_CLASSES: (1, 2)
      CLASS_KEY: ["center", "offset"]
DATASET:
  ROOT: "/home/nazib/Data/PASTIS/"
  DATASET: "pastis_panoptic"
  TRAIN_SPLIT: "PASTIS_train"
  NUM_CLASSES: 19
  TARGET_TYPE: instance
  TEST_SPLIT: 'PASTIS_test'
  CROP_SIZE: (128,128)
SOLVER:
  BASE_LR: 0.00005
  WEIGHT_DECAY: 0.0
  WEIGHT_DECAY_NORM: 0.0
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY_BIAS: 0.0
  OPTIMIZER: "adam"
  Epochs: 5
LOSS:
  SEMANTIC:
    NAME: "cross_entropy"
    IGNORE: 255
    WEIGHT: 2.5
  CENTER:
    NAME: 'mse'
    WEIGHT: 200.0
  OFFSET:
    NAME: 'l1'
    WEIGHT: 0.0
TRAIN:
  IMS_PER_BATCH: 2
  MAX_ITER: 90000
TEST:
  EVAL_INSTANCE: False
  EVAL_PANOPTIC: True
  CROP_SIZE: (1, 1)
  DEBUG: True
  EVAL_FOREGROUND: False
  FLIP_TEST: False
  FOREGROUND_FOLDER: foreground
  GPUS: (0,)
  INSTANCE_FOLDER: instance
  INSTANCE_SCORE_TYPE: semantic
  PANOPTIC_FOLDER: panoptic
  SEMANTIC_FOLDER: semantic
POST_PROCESSING:
  CENTER_THRESHOLD: 0.1
  NMS_KERNEL: 7
  TOP_K_INSTANCE: 200
  STUFF_AREA: 2048
OUTPUT_DIR: "./output/UnNormalized_5_epochs"
GPUS: (0,1)
WORKERS: 2